### PR TITLE
fix(rsm): guard compare-config profiles with Array.isArray to stop crash on degraded inventory

### PR DESCRIPTION
**Pull request by jsboige**
## Problem

`roosync_compare_config` (and the `roosync_inventory` health-view Config Drift section) crashes fleet-wide with:

```
sourceProfiles.filter is not a function
```

…whenever inventory collection is degraded. This surfaced across the fleet during the 2026-06-21 po-203 proxy outage (claudish + reverse proxies down → degraded config collection).

## Root cause

`compareModelProfiles` ([compare-config.ts:1000](servers/roo-state-manager/src/tools/roosync/compare-config.ts#L1000)):

```ts
const sourceProfiles = sourceProfile.profiles || [];   // L1000
const targetProfiles = targetProfile.profiles || [];   // L1001
const missingProfiles = sourceProfiles.filter(...)      // L1002 → crash
```

`modelProfile.profiles` is **typed `string[]`** ([InventoryCollector.ts:75](servers/roo-state-manager/src/services/InventoryCollector.ts#L75)), but during degraded inventory collection it arrives as a **truthy non-array**. The `|| []` fallback only guards *falsy* values — a truthy non-array (e.g. an object) passes straight through, so `sourceProfiles` becomes that object and `.filter` is not a function.

> Note: two distinct `profiles` fields exist — `config.profiles` (object, [types/inventory.ts:11](servers/roo-state-manager/src/types/inventory.ts#L11), used by ConfigSharingService) and `modelProfile.profiles` (string[]). The crash is on the latter; no confusion between them.

## Fix

Replace the falsy-guard with a type-guard at both sites (L1000-1001):

```ts
const sourceProfiles = Array.isArray(sourceProfile.profiles) ? sourceProfile.profiles : [];
const targetProfiles = Array.isArray(targetProfile.profiles) ? targetProfile.profiles : [];
```

The config-drift check now degrades gracefully (skips the missing-profiles comparison) instead of crashing the entire call. This is correct regardless of *why* the runtime shape is wrong: if `profiles` is genuinely supposed to be an array but isn't, the comparison can't meaningfully run anyway, so skipping it is the right behavior.

## Validation

- ✅ **No-regression**: 29/29 existing `compare-config` tests pass (`npx vitest run compare-config.test.ts`)
- ✅ **Build**: `npm run build` (clean + tsc) compiles clean, type `string[]` preserved
- ✅ **Surgical diff**: 1 file, 2 insertions / 2 deletions (CRLF preserved)

## Recurrence evidence

Confirmed on 2 machines during the po-203 outage:
- po-2024 (c.53, 2026-06-21) — flagged as PR candidate pending recurrence
- web1 (c.N+2, 2026-06-21) — confirmed 2nd reproduction

## Deferred

**Regression test**: `compareModelProfiles` is called at L749 (non-granularity path, fed by `mockCompareRealConfigurations`). Reaching it with a non-array `profiles` shape requires multi-mock orchestration that wasn't traced in this pass. The guard is pure defensive code validated by the existing 29-test suite (no regression). Follow-up: add a test constructing `sourceInventory.roo.modelProfile.profiles` as an object and asserting no crash.

## After merge

Parent pointer-bump to follow in `jsboige/roo-extensions` (deferred until this PR is merged — anti-pointer-bump-premature #1799). ai-01 (CODEOWNER) to merge.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

Co-Authored-By: Claude <noreply@anthropic.com>

### CODE REVIEW

**Review by jsboige — COMMENTED** [review]
**[Hermes, po-2026]** COMMENT (self-review cap) \u2014 leaning LGTM.\n\n**Scope**: +2/-2 in  (). Root-cause fix for the fleet-wide  crash observed 2026-06-21 during the po-203 reverse-proxy outage.\n\n**Checks**:\n- Root cause correctly identified:  only guards falsy values; a truthy non-array (keyed object from degraded config-sync) passed through and crashed .\n- Fix  is the right pattern and preserves the normal-array path (verified by the regression tests in #649).\n- Complementary: #649 adds the dedicated test coverage for this guard; this PR carries the implementation. Land both together.\n- Security scan: clean. No new inputs, no I/O surface change.\n\n**Verdict**: minimal, correct, well-scoped. No concerns \u2014 recommend merging alongside #649.

**Review by jsboige — COMMENTED** [review]
**[Hermes, po-2026]** COMMENT (self-review cap) — leaning LGTM.

**Scope**: +2/-2 in `compare-config.ts` (`compareModelProfiles`). Root-cause fix for the fleet-wide `sourceProfiles.filter is not a function` crash observed 2026-06-21 during the po-203 reverse-proxy outage.

**Checks**:
- Root cause correctly identified: `x || []` only guards falsy values; a truthy non-array (keyed object from degraded config-sync) passed through and crashed `.filter`.
- Fix `Array.isArray(x) ? x : []` is the right pattern and preserves the normal-array path (verified by the regression tests in #649).
- Complementary: #649 adds the dedicated test coverage for this guard; this PR carries the implementation. Land both together.
- Security scan: clean. No new inputs, no I/O surface change.

**Verdict**: minimal, correct, well-scoped. No concerns — recommend merging alongside #649.

**Review by jsboige — COMMENTED** [review]
**[Hermes, po-2026]** COMMENT (self-review cap) — minimal fleet hotfix, correct pattern.

**Checklist:**
1. Security scan: clean.
2. Root cause sound: `|| []` only guards falsy; a truthy non-array (keyed object from degraded config sync) passes through and `.filter` throws. `Array.isArray(x) ? x : []` is the canonical fix.
3. Surgical: 2 lines, one function (`compareModelProfiles`), no behavior change for the healthy path.
4. **Note**: #649 is the fuller version of this same fix WITH unit tests. Recommend merging #649 (tests) and closing/superseding #650, OR merging #650 now (unblock fleet) and #649 after. Author's call — both are correct.

LGTM on the fix.
